local awful     = require("awful")
local naughty   = require("naughty")
local beautiful = require("beautiful")
local wibox     = require('wibox')
local pairs     = pairs
--local layout    = require('wibox.layout')
local lgi = require("lgi")
local cairo = lgi.cairo
local Pango = lgi.Pango
local PangoCairo = lgi.PangoCairo
--local text_box  = require('blingbling.text_box')
--local text_box  = require('wibox.widget.textbox')

local capi      = {
   mouse = mouse,
   screen = screen,
   keygrabber = keygrabber,
   client = client
}

-- BUG: when settings are taken from `beautiful` defaults, the default them is used
-- because the module is loaded before the beautiful theme is changed.
-- Workaround: the default commands is not a table, but is generated by a function
local system = {}
system.settings = {
    border_width = 5,
    font = "Sans 48"
}

local function get_styles(styles)
	local styles = styles or {}
    local res = {}
	res.fg_normal    = styles.fg_normal    or system.settings.fg_normal    or beautiful.bg_normal or "#232323"   --light black
	res.bg_normal    = styles.bg_normal    or system.settings.bg_normal    or beautiful.fg_normal or "#999999"   --light white
	res.fg_focus     = styles.fg_focus     or system.settings.fg_focus     or beautiful.fg_focus  or "#ffffff"   --white
	res.bg_focus     = styles.bg_focus     or system.settings.bg_focus     or beautiful.bg_focus  or "#b9214f"   --red
	res.border_color = styles.border_color or system.settings.border_color or beautiful.bg_focus  or "#b9214f"   --red
	res.border_width = styles.border_width or system.settings.border_width or 5
	res.height       = styles.height       or system.settings.height       or 10
	res.width        = styles.width        or system.settings.width        or 100
	res.font         = styles.font         or system.settings.font         or "Sans 48"
		
	return res
end

-- List command names, function, (optional) icon
local function default_commands(DEBUG)
    local DEBUG = DEBUG or false
    local comm = {}
    if not DEBUG then
        comm = {
            {"Shutdown"    , 'systemctl poweroff'         , beautiful.menu_shutdown          },
            {"Reboot"      , 'systemctl reboot'           , beautiful.menu_reboot            },
            {"Lock"        , 'systemctl lock'             , beautiful.menu_lock              },
            {"Suspend"     , 'systemctl suspend'          , beautiful.menu_suspend           },
            {"Logout"      , awesome.quit                 , beautiful.menu_logout            }
        }
    else
        local zen_cmd = 'zenity --width=100 --height=250 --list --text="Select logout action" --title="Logout"  --column "Actions"'
        comm = {
            {"Shutdown", zen_cmd .. ' Shutdown' , beautiful.menu_shutdown},
            {"Reboot"  , zen_cmd .. ' Reboot'   , beautiful.menu_reboot},
            {"Lock"    , zen_cmd .. ' Lock'     , beautiful.menu_lock},
            {"Suspend" , zen_cmd .. ' Suspend'  , nil},
            {"Logout"  , function() naughty.notify({ title = "Logout", text = "Logout" }) end , beautiful.menu_logout}
        }
    end
    return comm
end

-- {{{ Dialog Zenity
function system.logout_dialog_zenity ()
    return function ()
        awful.spawn.with_shell(awful.util.get_configuration_dir().."/lib/ShutdownDialog2.sh --gui")
    end
end
-- }}}

-- {{{ Dialog menu
local function menu_size_hints(c, settings)
    local settings = settings

    -- Get the max height and width of the options textbox
    local max_height = 0
    local max_width = 0
    local w,h = 0
    local label = wibox.widget.textbox()
    label:set_font(settings.font)
    for i,k in ipairs(c) do
        label:set_text(k[1])
        w,h = label:get_preferred_size(awful.screen.focused())
        max_width  = max_width  > w and max_width  or w
        max_height = max_height > h and max_height or h
    end

    -- Set the height and width to the max values
    settings.height = max_height + 2*settings.border_width
    settings.width = max_width + max_height + 4*settings.border_width  -- add max_height because of the icon space
    return settings
end

function system.logout_dialog_menu ()
    local settings = get_styles()
    local c = default_commands()
    -- Add `cancel` option
    table.insert(c, {"--------", nil})
    table.insert(c, {"cancel", function () end})

    -- Get size hints from creating fake textboxes
    settings = menu_size_hints(c, settings)

    -- Create new menu
    local menu = awful.menu.new({ items = c, theme=settings})

    local screen_geometry = awful.screen.focused().workarea
    local coords = {}
    
    coords.x = screen_geometry.x + (screen_geometry.width  -  menu.wibox.width)/2.
    coords.y = screen_geometry.y + (screen_geometry.height - menu.wibox.height)/2.

    menu:show({coords=coords})
end
-- }}}

-- {{{ Dialog wibox
-- Not compatible Awesome>4.0
local function apply_style(widget, style)
	for k,v in pairs(style) do
		if widget['set_'..k] ~= nil and type(widget['set_'..k]) == "function" then
			widget['set_' ..k](widget, v)
		end
	end
end

local function launch_command(cmd)
    -- Try to run the command in lua
    if type(cmd) == 'string' then
        --awful.util.spawn(cmd)
        awful.util.spawn_with_shell(cmd)
    else
        pcall(cmd)
    end
end

local function show_wibox(box)
    local current_screen = capi.mouse.screen
    local screen_geometry = capi.screen[current_screen].workarea
    local x,y =0
    
    x = screen_geometry.x + (screen_geometry.width  -  box.width)/2.
    y = screen_geometry.y + (screen_geometry.height - box.height)/2.
    
    box:geometry({--width = wibox.width, 
                    --height = wibox.height,
                    x = x,
                    y = y
    })
    box.visible = true
end

local function hide_wibox(box)
    box.visible=false
end


function system.logout_dialog_wibox ()
	local ml = 2 
	local mr = 2
	local mt = 2
	local mb = 2

    local max_height = 0
    local max_width = 0

    local settings = get_styles()
	local dialog = {}
    dialog.widget = {}

    local c = default_commands()
    -- Add `cancel` option
    table.insert(c, {"--------", nil})
    table.insert(c, {"cancel", function() hide_wibox(dialog.widget) end})

    local style = { width=100, height=10, h_margin=2, v_margin=2, 
                    background_color=beautiful.bg_normal, background_text_border=beautiful.fg_normal, 
                    text_background_color=beautiful.bg_normal, rounded_size=0, 
                    text_color=beautiful.fg_normal, font_size=50, font="sans"}
    local unfocus_style = {background_color=beautiful.bg_normal, text_background_color=beautiful.bg_normal, text_color=beautiful.fg_normal}
    local focus_style   = {background_color=beautiful.bg_focus, text_background_color=beautiful.bg_focus, text_color=beautiful.fg_focus}

    -- Create dialog options
    dialog.entries = {}
    for i =1,#c do
        dialog.entries[i] = {}
        dialog.entries[i].widget = wibox.widget.textbox {style}
        dialog.entries[i].widget:set_text(c[i][1])
        dialog.entries[i].margin = wibox.container.margin(dialog.entries[i].widget, ml,mr,mt,mb)

        -- Attach mouse action
        if i ~= (#c-1) then
            dialog.entries[i].widget:buttons(awful.util.table.join(
                    awful.button({ },  1, function() launch_command(c[i][2]) end, function() hide_wibox(dialog.widget) end ) ))
            dialog.entries[i].widget:connect_signal("mouse::enter", function() apply_style(dialog.entries[i].widget, focus_style) end)
            dialog.entries[i].widget:connect_signal("mouse::leave", function() apply_style(dialog.entries[i].widget, unfocus_style) end)
        end

        -- Calculate max size
        w,h = dialog.entries[i].margin:fit(0,0)
        max_width = max_width > w and max_width or w
        max_height = max_height > h and max_height or h
    end

    -- Resize dialog
    dialog.column = layout.fixed.vertical()
    for i =1,#c do
        -- Make identical cases
        dialog.entries[i].widget:set_width(max_width)
        dialog.entries[i].widget:set_height(max_height)
        --dialog.entries[i].widget:set_align("center")
        --dialog.entries[i].widget:set_valign("center")
        dialog.column:add(dialog.entries[i].margin)
    end
    
    local dialog_height = #c * (max_height + 4)   -- include margin
    local dialog_width  = max_width
    --local dialog_height = settings.height
    --local dialog_width  = settings.width
    dialog.widget = wibox({ontop = true,
                        height = dialog_height,
                        width  = dialog_width   })
    dialog.widget:set_widget(dialog.column)
    dialog.widget:buttons(awful.util.table.join(
                awful.button({ },  3, function() hide_wibox(dialog.widget) end ) ))

    show_wibox(dialog.widget)
end
-- }}}


return system
